ProjectRPG.Web/Areas/Administrador/Controllers/ArmaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectRPG.DataAccess.Repository.IRepository;
using ProjectRPG.Models;
using ProjectRPG.Utilitarios;

namespace ProjectRPG.Web.Areas.Administrador.Controllers
{
    [Area("Administrador")]
    [Authorize(Roles = SD.Role_Administrador)]
    public class ArmaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ArmaController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var lista = _unitOfWork.Arma.BuscarTodos().ToList();
            return View(lista);
        }

        public IActionResult AdicionarOuEditar(int? id)
        {
            if (id == null || id == 0)
            {
                //create
                return View();
            }
            else
            {
                //update
                Arma arma = _unitOfWork.Arma.Buscar(u => u.Id == id);
                return View(arma);
            }
        }

        [HttpPost]
        public IActionResult AdicionarOuEditar(Arma arma)
        {
            if (ModelState.IsValid)
            {
                if (arma.Id == null || arma.Id == 0)
                {
                    arma.Equipado = false;
                    _unitOfWork.Arma.Adicionar(arma);
                    _unitOfWork.Salvar();
                    TempData["success"] = "Arma adicionada!";
                }
                else
                {
                    _unitOfWork.Arma.Alterar(arma);
                    _unitOfWork.Salvar();
                    TempData["success"] = "Arma editada!";
                }
                    
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Arma? arma = _unitOfWork.Arma.Buscar(u => u.Id == id);

            if (arma == null)
            {
                return NotFound();
            }
            return View(arma);
        }


        [HttpPost, ActionName("Excluir")]
        public IActionResult ExcluirPOST(int? id)
        {
            Arma? arma = _unitOfWork.Arma.Buscar(u => u.Id == id);
            if (arma == null)
            {
                return NotFound();
            }
            _unitOfWork.Arma.Excluir(arma);
            _unitOfWork.Salvar();
            TempData["success"] = "Arma excluída!";
            return RedirectToAction("Index");
        }
    }
}

ProjectRPG.Web/Areas/Administrador/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectRPG.DataAccess.Repository.IRepository;
using ProjectRPG.Models;
using ProjectRPG.Models.ViewModel;
using ProjectRPG.Utilitarios;


namespace ProjectRPG.Web.Areas.Administrador.Controllers
{
    [Area("Administrador")]
    //[Authorize(Roles = SD.Role_Administrador)]
    public class UsuarioController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<RPGUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UsuarioController(IUnitOfWork unitOfWork, RoleManager<IdentityRole> roleManager, UserManager<RPGUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var listaVM = new List<UsuarioViewModel>();
            var lista = _unitOfWork.RPGUser.BuscarTodos();
            foreach (var item in lista)
            {
                var rolesDoUsuario = await _userManager.GetRolesAsync(item);
                var vm = new UsuarioViewModel();
                vm.Usuario = item;
                vm.Role = rolesDoUsuario.FirstOrDefault().ToString();
                listaVM.Add(vm);
            }
            return View(listaVM);
        }


        public async Task<IActionResult> AlterarPerfil(string id)
        {
            if (id == null) return NotFound();
            else
            {
                RPGUser? usuario = _unitOfWork.RPGUser.Buscar(u => u.Id == id);
                if (usuario == null)  return NotFound();
                else
                {
                    var rolesDoUsuario = await _userManager.GetRolesAsync(usuario);
                    var roleList = _roleManager.Roles.Select(x => x.Name).Select(i => new SelectListItem
                    {
                        Text = i,
                        Value = i
                    });

                    var vm = new UsuarioViewModel();
                    vm.Usuario = usuario;
                    vm.Role = rolesDoUsuario.FirstOrDefault().ToString();
                    vm.RoleList = roleList;
                    return View(vm);
                }
            }
        }

        [HttpPost]
        public async Task<IActionResult> AlterarPerfil(UsuarioViewModel vm)
        {
            if (vm == null) return NotFound();
            if(vm.Role != "Administrador" &&  vm.Role != "Jogador") ModelState.AddModelError("role", "O usuário só pode ser Administrador ou Jogador");
            if (ModelState.IsValid)
            {
                RPGUser usuario = _unitOfWork.RPGUser.Buscar(u => u.Id == vm.Usuario.Id);
                if (usuario == null) return NotFound();

                var rolesDoUsuario = await _userManager.GetRolesAsync(usuario);
                await _userManager.RemoveFromRolesAsync(usuario, rolesDoUsuario);
                await _userManager.AddToRoleAsync(usuario, vm.Role);
                TempData["success"] = "Perfil alterado com sucesso!";
                return RedirectToAction("Index");
            }
			TempData["error"] = "Perfil não pode ser alterado!";
			return View();
        }


        public async Task<IActionResult> Excluir(string id)
        {
            if (id == null) return NotFound();
            else
            {
                RPGUser? usuario = _unitOfWork.RPGUser.Buscar(u => u.Id == id);
                if (usuario == null) return NotFound();
                else
                {
                    var rolesDoUsuario = await _userManager.GetRolesAsync(usuario);
                    var vm = new UsuarioViewModel();
                    vm.Usuario = usuario;
                    vm.Role = rolesDoUsuario.FirstOrDefault().ToString();
                    return View(vm);
                }
            }
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(UsuarioViewModel vm)
        {
            if (vm == null) return NotFound();
            else
            {
                RPGUser? usuario = _unitOfWork.RPGUser.Buscar(u => u.Id == vm.Usuario.Id);
                if (usuario == null) return NotFound();
                else
                {
                    var rolesDoUsuario = await _userManager.GetRolesAsync(usuario);
                    await _userManager.RemoveFromRolesAsync(usuario, rolesDoUsuario);

                    _unitOfWork.RPGUser.Excluir(usuario);
                    _unitOfWork.Salvar();

                    return RedirectToAction("Index");
                }
            }
        }
    }
}

ProjectRPG.Web/Areas/Administrador/Views/Usuario/AlterarPerfil.cshtml
@using Microsoft.AspNetCore.Identity
@model UsuarioViewModel

@{
    ViewData["Title"] = "Alterar Perfil de " + Model.Usuario.NomeUsuario;
}

@inject SignInManager<RPGUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <a asp-controller="Arma" asp-action="Index">
        <svg id="btn-voltar" xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="#008C59" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"></path>
        </svg>
    </a>

    <div class="container cartao">
        <div class="cartao-topo adicionar">
            <h2 class="cartao-titulo">@ViewData["Title"]</h2>
        </div>

        <div id="cartao-conteudo" class="cartao-conteudo adicionar">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                <input asp-for="Usuario.Id" hidden />

                <div class="container-botao" style="margin-bottom: 40px;">
                    <select asp-for="Role" asp-items="@Model.RoleList" class="form-select">
                        <option disabled selected>-Selecionar Perfil-</option>
                    </select>
                </div>

                <div class="container-botao">
                    <button type="submit" class="col-5 botao-submit">Salvar</button>
                </div>
            </form>
        </div>
    </div>

}
else
{
    if (User.IsInRole("Administrador"))
    {
        <script type="text/javascript">
            window.location.href = "/Administrador/Home/Index";
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.location.href = "/Jogador/Home/Index";
        </script>
    }

}

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

ProjectRPG.Web/Areas/Administrador/Views/Usuario/Excluir.cshtml
@using Microsoft.AspNetCore.Identity
@model UsuarioViewModel

@inject SignInManager<RPGUser> SignInManager
@inject UserManager<RPGUser> UserManager

@{
    ViewData["Title"] = "Excluir Usuário " + Model.Usuario.NomeUsuario;
}



@if (SignInManager.IsSignedIn(User))
{
    <a asp-controller="Usuario" asp-action="Index">
        <svg id="btn-voltar" xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="#008C59" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"></path>
        </svg>
    </a>
    <div class="container cartao">
        <div class="cartao-topo adicionar">
            <h2 class="cartao-titulo">@ViewData["Title"]</h2>
        </div>

        <div id="cartao-conteudo" class="cartao-conteudo adicionar">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                <input asp-for="Usuario.Id" hidden />

                <label asp-for="Usuario.Email" class="label-cadastro"></label>
                <input asp-for="Usuario.Email" class="input-cadastro" disabled />

                <label asp-for="Usuario.PhoneNumber" class="label-cadastro">Número de Telefone</label>
                <input asp-for="Usuario.PhoneNumber" class="input-cadastro" disabled />

                <label asp-for="Usuario.DataNascimento" class="label-cadastro"></label>
                <input asp-for="Usuario.DataNascimento" class="input-cadastro" disabled />

                <label asp-for="Role" class="label-cadastro"></label>
                <input asp-for="Role" class="input-cadastro" disabled />

                <div class="container-botao">
                    <button type="submit" class="col-5 botao-submit">Excluir</button>
                </div>
            </form>
        </div>
    </div>
}
else
{
    if (User.IsInRole("Administrador"))
    {
        <script type="text/javascript">
            window.location.href = "/Administrador/Home/Index";
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.location.href = "/Jogador/Home/Index";
        </script>
    }

}

ProjectRPG.Web/Areas/Administrador/Views/Usuario/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model List<UsuarioViewModel>

@{
    ViewData["Title"] = "Visualizar Usuários";
}
@inject SignInManager<RPGUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <a asp-controller="Home" asp-action="Index">
        <svg id="btn-voltar" xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="#008C59" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"></path>
        </svg>
    </a>
    <div class="container cartao">
        <div class="cartao-topo visualizar">
            <h2 class="cartao-titulo">@ViewData["Title"]</h2>
        </div>

        <div id="cartao-conteudo" class="cartao-conteudo visualizar">

            <div class="div-tabela">
                <table class="tabela table-striped">
                    <thead class="header-tabela">
                        <tr>
                            <th class ="coluna-1">Nome de Usuário</th>
                            <th class="coluna-1">Email</th>
                            <th class="coluna-1">Número de Telefone</th>
                            <th class="coluna-1">Data de Nascimento</th>
                            <th class="coluna-1">Perfil</th>
                            <th class="coluna-10">Opções</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        @foreach (var user in Model)
                        {
                            <tr>
                                <td class="coluna-1">@user.Usuario.NomeUsuario</td>
                                <td class="coluna-1">@user.Usuario.Email</td>
                                <td class="coluna-1">@user.Usuario.PhoneNumber</td>
                                <td class="coluna-1">@user.Usuario.DataNascimento</td>
                                <td class="coluna-1">@user.Role</td>
                                <td class="coluna-1">
                                    <div class="w-75 btn-group" role="group">
                                        <a asp-controller="Usuario" asp-action="AlterarPerfil" asp-route-id="@user.Usuario.Id" class="btn btn-dark mx-2">
                                            <i class="bi bi-pencil-square"></i> Alterar Perfil
                                        </a>
                                        <a asp-controller="Usuario" asp-action="Excluir" asp-route-id="@user.Usuario.Id" class="btn btn-danger mx-2">
                                            <i class="bi bi-trash-fill"></i> Excluir
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>

    </div>
}
else
{
    if (User.IsInRole("Administrador"))
    {
        <script type="text/javascript">
            window.location.href = "/Administrador/Home/Index";
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.location.href = "/Jogador/Home/Index";
        </script>
    }

}