ProjectRPG.Web/Areas/Administrador/Controllers/AtributoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectRPG.DataAccess.Repository.IRepository;
using ProjectRPG.Models;
using ProjectRPG.Models.ViewModel;
using ProjectRPG.Utilitarios;

namespace ProjectRPG.Web.Areas.Administrador.Controllers
{
    [Area("Administrador")]
    [Authorize(Roles = SD.Role_Administrador)]
    public class AtributoController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public AtributoController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<AtributoViewModel> lista = new List<AtributoViewModel>();

            foreach (Atributo item in _unitOfWork.Atributo.BuscarTodos().ToList()){
                lista.Add(new AtributoViewModel()
                {
                    Atributo = item,
                    Personagem = _unitOfWork.Personagem.Buscar(x => x.Id == item.PersonagemId)
                }); 
            }
            return View(lista);
        }

        public IActionResult AdicionarOuEditar(int? id)
        {
            var personagens = _unitOfWork.Personagem.BuscarTodos().ToList();
            var viewModel = new AtributoViewModel();
            viewModel.PersonagensSelectList = personagens
                .Select(p => new SelectListItem
                {
                    Value = p.Id.ToString(),
                    Text = p.Nome
                });
            if (id == null || id == 0)
            {
                return View(viewModel);
            }
            else
            {
                viewModel.Atributo = _unitOfWork.Atributo.Buscar(u => u.Id == id);
                viewModel.Personagem = _unitOfWork.Personagem.Buscar(x => x.Id == viewModel.Atributo.PersonagemId);
                return View(viewModel);
            }
        }

        [HttpPost]
        public IActionResult AdicionarOuEditar(AtributoViewModel viewModel)
        {
            viewModel.PersonagensSelectList = _unitOfWork.Personagem.BuscarTodos().ToList()
                .Select(p => new SelectListItem
                {
                    Value = p.Id.ToString(),
                    Text = p.Nome
                });
            var personagem = _unitOfWork.Personagem.Buscar(x => x.Id == viewModel.Personagem.Id);
            if (ModelState.IsValid)
            {
                var atributo = new Atributo()
                {
                    Corpo = viewModel.Atributo.Corpo,
                    Foco = viewModel.Atributo.Foco,
                    Mente = viewModel.Atributo.Mente,
                    Reacao = viewModel.Atributo.Reacao,
                    PersonagemId = personagem.Id,
                    Personagem = viewModel.Personagem
                };

                if (viewModel.Atributo.Id == null || viewModel.Atributo.Id == 0)
                {
                    _unitOfWork.Atributo.Adicionar(atributo);
                    _unitOfWork.Salvar();
                    TempData["success"] = "Atributo adicionado!";
                }
                else
                {
                    _unitOfWork.Atributo.Alterar(atributo);
                    _unitOfWork.Salvar();
                    TempData["success"] = "Atributo editado!";
                }

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Atributo? atributo = _unitOfWork.Atributo.Buscar(u => u.Id == id);

            if (atributo == null)
            {
                return NotFound();
            }
            return View(atributo);
        }


        [HttpPost, ActionName("Excluir")]
        public IActionResult ExcluirPOST(int? id)
        {
            Atributo? atributo = _unitOfWork.Atributo.Buscar(u => u.Id == id);
            if (atributo == null)
            {
                return NotFound();
            }
            _unitOfWork.Atributo.Excluir(atributo);
            _unitOfWork.Salvar();
            TempData["success"] = "Atributo excluído!";
            return RedirectToAction("Index");
        }
    }
}

ProjectRPG.Web/Areas/Administrador/Views/Atributo/AdicionarOuEditar.cshtml
@using Microsoft.AspNetCore.Identity
@model AtributoViewModel

@{
    var acao = (Model != null ? "Editar" : "Adicionar");
    ViewData["Title"] = acao + " Atributo";
}

@inject SignInManager<RPGUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <a asp-controller="Atributo" asp-action="Index">
        <svg id="btn-voltar" xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="#008C59" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"></path>
        </svg>
    </a>
    
    <div class="container cartao">
        <div class="cartao-topo adicionar">
            <h2 class="cartao-titulo">@ViewData["Title"]</h2>
        </div>

        <div id="cartao-conteudo" class="cartao-conteudo adicionar">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>

                <label asp-for="Atributo.Corpo" class="label-cadastro"></label>
                <input asp-for="Atributo.Corpo" class="input-cadastro number" aria-required="true" min="1" max="20" />
                <span asp-validation-for="Atributo.Corpo" class="text-danger row alerta-login"></span>

                <label asp-for="Atributo.Foco" class="label-cadastro"></label>
                <input asp-for="Atributo.Foco" class="input-cadastro number" aria-required="true" min="1" max="20" />
                <span asp-validation-for="Atributo.Foco" class="text-danger row alerta-login"></span>

                <label asp-for="Atributo.Mente" class="label-cadastro"></label>
                <input asp-for="Atributo.Mente" class="input-cadastro number" aria-required="true" min="1" max="20" />
                <span asp-validation-for="Atributo.Mente" class="text-danger row alerta-login"></span>

                <label asp-for="Atributo.Reacao" class="label-cadastro"></label>
                <input asp-for="Atributo.Reacao" class="input-cadastro number" aria-required="true" min="1" max="20" />
                <span asp-validation-for="Atributo.Reacao" class="text-danger row alerta-login"></span>

                <label asp-for="Personagem.Id" class="label-cadastro">Personagem</label>
                <select asp-for="Personagem.Id" asp-items="Model.PersonagensSelectList">
                    <option value="">Selecione um personagem</option>
                </select>

                <div class="container-botao">
                    <button type="submit" class="col-5 botao-submit">@acao</button>
                </div>
            </form>
        </div>
    </div>

}
else
{
    if (User.IsInRole("Administrador"))
    {
        <script type="text/javascript">
            window.location.href = "/Administrador/Home/Index";
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.location.href = "/Jogador/Home/Index";
        </script>
    }

}

ProjectRPG.Web/Areas/Administrador/Views/Atributo/Excluir.cshtml
@using Microsoft.AspNetCore.Identity
@model AtributoViewModel

@{
    ViewData["Title"] = "Excluir Atributo";
}

@inject SignInManager<RPGUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <a asp-controller="Atributo" asp-action="Index">
        <svg id="btn-voltar" xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="#008C59" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"></path>
        </svg>
    </a>
    <div class="container cartao">
        <div class="cartao-topo adicionar">
            <h2 class="cartao-titulo">@ViewData["Title"]</h2>
        </div>

        <div id="cartao-conteudo" class="cartao-conteudo adicionar">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>

                <label asp-for="Atributo.Corpo" class="label-cadastro"></label>
                <input asp-for="Atributo.Corpo" class="input-cadastro number" disabled />

                <label asp-for="Atributo.Foco" class="label-cadastro"></label>
                <input asp-for="Atributo.Foco" class="input-cadastro number" disabled />

                <label asp-for="Atributo.Mente" class="label-cadastro"></label>
                <input asp-for="Atributo.Mente" class="input-cadastro number" disabled />

                <label asp-for="Atributo.Reacao" class="label-cadastro"></label>
                <input asp-for="Atributo.Reacao" class="input-cadastro number" disabled />

                <label asp-for="Personagem.Nome" class="label-cadastro"></label>
                <input asp-for="Personagem.Nome" class="input-cadastro" disabled />

                <div class="container-botao">
                    <button type="submit" class="col-5 botao-submit">Excluir</button>
                </div>
            </form>
        </div>
    </div>
}
else
{
    if (User.IsInRole("Administrador"))
    {
        <script type="text/javascript">
            window.location.href = "/Administrador/Home/Index";
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.location.href = "/Jogador/Home/Index";
        </script>
    }

}

ProjectRPG.Web/Areas/Administrador/Views/Atributo/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model List<AtributoViewModel>

@{
    ViewData["Title"] = "Visualizar Atributos";
}

@inject SignInManager<RPGUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <a asp-controller="Home" asp-action="Index">
        <svg id="btn-voltar" xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="#008C59" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"></path>
        </svg>
    </a>
    <div class="container cartao">
        <div class="cartao-topo visualizar">
            <h2 class="cartao-titulo">@ViewData["Title"]</h2>
        </div>

        <div id="cartao-conteudo" class="cartao-conteudo visualizar">
            <div class="div-adicionar">
                <a asp-area="Administrador" asp-controller="Atributo" asp-action="AdicionarOuEditar" class="btn btn-dark btn-adicionar">
                    <svg id="icone-add" xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#f5f5f5" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"></path>
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"></path>
                    </svg>
                    Adicionar Arma
                </a>
            </div>

            <div class="div-tabela">
                <table class="tabela table-striped">
                    <thead class="header-tabela">
                        <tr>
                            <th class="coluna-2">Jogador</th>
                            <th class="coluna-1">Personagem</th>
                            <th class="coluna-2">Corpo</th>
                            <th class="coluna-3">Foco</th>
                            <th class="coluna-4">Mente</th>
                            <th class="coluna-5">Reação</th>
                            <th class="coluna-10">Opções</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        @foreach (var atributo in Model)
                        {
                            <tr>
                                <td class="coluna-1">@atributo.Personagem</td>
                                <td class="coluna-2">@atributo.Personagem</td>
                                <td class="coluna-3">@atributo.Atributo.Corpo</td>
                                <td class="coluna-4">@atributo.Atributo.Foco</td>
                                <td class="coluna-6">@atributo.Atributo.Mente</td>
                                <td class="coluna-7">@atributo.Atributo.Reacao</td>
                                <td class="coluna-10">
                                    <div class="w-75 btn-group" role="group">
                                        <a asp-controller="Atributo" asp-action="AdicionarOuEditar" asp-route-id="@atributo.Atributo.Id" class="btn btn-dark mx-2" id="btn-editar">
                                            <i class="bi bi-pencil-square"></i> Editar
                                        </a>
                                        <a asp-controller="Atributo" asp-action="Excluir" asp-route-id="@atributo.Atributo.Id" class="btn btn-danger mx-2">
                                            <i class="bi bi-trash-fill"></i> Excluir
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>

    </div>
}
else
{
    if (User.IsInRole("Administrador"))
    {
        <script type="text/javascript">
            window.location.href = "/Administrador/Home/Index";
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.location.href = "/Jogador/Home/Index";
        </script>
    }

}