ProjectRPG.Web/Areas/Administrador/Controllers/ArmaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectRPG.DataAccess.Repository.IRepository;
using ProjectRPG.Models;
using ProjectRPG.Utilitarios;

namespace ProjectRPG.Web.Areas.Administrador.Controllers
{
    [Area("Administrador")]
    [Authorize(Roles = SD.Role_Administrador)]
    public class ArmaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ArmaController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var lista = _unitOfWork.Arma.BuscarTodos().ToList();
            return View(lista);
        }

        public IActionResult AdicionarOuEditar(int? id)
        {
            if (id == null || id == 0)
            {
                //create
                return View();
            }
            else
            {
                //update
                Arma arma = _unitOfWork.Arma.Buscar(u => u.Id == id);
                return View(arma);
            }
        }

        [HttpPost]
        public IActionResult AdicionarOuEditar(Arma arma)
        {
            if (ModelState.IsValid)
            {
                if (arma.Id == null || arma.Id == 0)
                {
                    arma.Equipado = false;
                    _unitOfWork.Arma.Adicionar(arma);
                    _unitOfWork.Salvar();
                    TempData["success"] = "Arma adicionada!";
                }
                else
                {
                    _unitOfWork.Arma.Alterar(arma);
                    _unitOfWork.Salvar();
                    TempData["success"] = "Arma editada!";
                }
                    
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Arma? arma = _unitOfWork.Arma.Buscar(u => u.Id == id);

            if (arma == null)
            {
                return NotFound();
            }
            return View(arma);
        }


        [HttpPost, ActionName("Excluir")]
        public IActionResult ExcluirPOST(int? id)
        {
            Arma? arma = _unitOfWork.Arma.Buscar(u => u.Id == id);
            if (arma == null)
            {
                return NotFound();
            }
            _unitOfWork.Arma.Excluir(arma);
            _unitOfWork.Salvar();
            TempData["success"] = "Arma excluída!";
            return RedirectToAction("Index");
        }
    }
}

ProjectRPG.Web/Areas/Administrador/Controllers/PersonagemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectRPG.DataAccess.Repository.IRepository;
using ProjectRPG.Models;
using ProjectRPG.Utilitarios;

namespace ProjectRPG.Web.Areas.Administrador.Controllers
{
    [Area("Administrador")]
    [Authorize(Roles = SD.Role_Administrador)]
    public class PersonagemController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public PersonagemController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var lista = _unitOfWork.Personagem.BuscarTodos().ToList();
            return View(lista);
        }

        public IActionResult AdicionarOuEditar(int? id)
        {
            if (id == null || id == 0)
            {
                //create
                return View();
            }
            else
            {
                //update
                Personagem personagem = _unitOfWork.Personagem.Buscar(u => u.Id == id);
                return View(personagem);
            }
        }

        [HttpPost]
        public IActionResult AdicionarOuEditar(Personagem personagem)
        {
            if (ModelState.IsValid)
            {
                if (personagem.Id == null || personagem.Id == 0)
                {
                    _unitOfWork.Personagem.Adicionar(personagem);
                    _unitOfWork.Salvar();
                    TempData["success"] = "Arma adicionada!";
                }
                else
                {
                    _unitOfWork.Personagem.Alterar(personagem);
                    _unitOfWork.Salvar();
                    TempData["success"] = "Arma editada!";
                }

                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Personagem? personagem = _unitOfWork.Personagem.Buscar(u => u.Id == id);

            if (personagem == null)
            {
                return NotFound();
            }
            return View(personagem);
        }


        [HttpPost, ActionName("Excluir")]
        public IActionResult ExcluirPOST(int? id)
        {
            Personagem? personagem = _unitOfWork.Personagem.Buscar(u => u.Id == id);
            if (personagem == null)
            {
                return NotFound();
            }
            _unitOfWork.Personagem.Excluir(personagem);
            _unitOfWork.Salvar();
            TempData["success"] = "Arma excluída!";
            return RedirectToAction("Index");
        }
    }
}

ProjectRPG.Web/Areas/Jogador/Controllers/PersonagemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectRPG.DataAccess.Repository.IRepository;
using ProjectRPG.Utilitarios;

namespace ProjectRPG.Web.Areas.Jogador.Controllers
{
    [Area("Jogador")]
    //[Authorize(Roles = SD.Role_Jogador)]
    public class PersonagemController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public PersonagemController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var personagem = _unitOfWork.Personagem.Buscar(x => x.Id == 1);
            return View(personagem);
        }
    }
}

ProjectRPG.Web/Areas/Administrador/Views/Personagem/AdicionarOuEditar.cshtml
@using Microsoft.AspNetCore.Identity
@model Personagem

@{
    var acao = (Model != null ? "Editar" : "Adicionar");
    ViewData["Title"] = acao + " Personagem";
}

@inject SignInManager<RPGUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <a asp-controller="Personagem" asp-action="Index">
        <svg id="btn-voltar" xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="#008C59" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"></path>
        </svg>
    </a>

    <div class="container cartao">
        <div class="cartao-topo adicionar">
            <h2 class="cartao-titulo">@ViewData["Title"]</h2>
        </div>

        <div id="cartao-conteudo" class="cartao-conteudo adicionar">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>

                <label asp-for="Nome" class="label-cadastro"></label>
                <input asp-for="Nome" class="input-cadastro" aria-required="true" />
                <span asp-validation-for="Nome" class="text-danger row alerta-login"></span>

                <label asp-for="Especie" class="label-cadastro"></label>
                <input asp-for="Especie" class="input-cadastro" aria-required="true" />
                <span asp-validation-for="Especie" class="text-danger row alerta-login"></span>

                <label asp-for="Aparencia" class="label-cadastro descricao"></label>
                <div class="descricao">
                    <textarea asp-for="Aparencia" class="input-cadastro" aria-required="true"></textarea>
                </div>
                <span asp-validation-for="Aparencia" class="text-danger row alerta-login"></span>

                <label asp-for="PvTotal" class="label-cadastro"></label>
                <input asp-for="PvTotal" class="input-cadastro number" aria-required="true" min="1" max="5000" />
                <span asp-validation-for="PvTotal" class="text-danger row alerta-login"></span>

                <label asp-for="PvAtual" class="label-cadastro"></label>
                <input asp-for="PvAtual" class="input-cadastro number" aria-required="true" min="1" max="10000" />
                <span asp-validation-for="PvAtual" class="text-danger row alerta-login"></span>

                <label asp-for="Deslocamento" class="label-cadastro"></label>
                <input asp-for="Deslocamento" class="input-cadastro number" aria-required="true" min="1" max="10000" />
                <span asp-validation-for="Deslocamento" class="text-danger row alerta-login"></span>

                <label asp-for="Evasao" class="label-cadastro"></label>
                <input asp-for="Evasao" class="input-cadastro number" aria-required="true" min="1" max="10000" />
                <span asp-validation-for="Evasao" class="text-danger row alerta-login"></span>

                <label asp-for="Tag" class="label-cadastro"></label>
                <input asp-for="Tag" class="input-cadastro" aria-required="true" />
                <span asp-validation-for="Tag" class="text-danger row alerta-login"></span>

                <div class="container-botao">
                    <button type="submit" class="col-5 botao-submit">@acao</button>
                </div>
            </form>
        </div>
    </div>

}
else
{
    if (User.IsInRole("Administrador"))
    {
        <script type="text/javascript">
            window.location.href = "/Administrador/Home/Index";
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.location.href = "/Jogador/Home/Index";
        </script>
    }

}

ProjectRPG.Web/Areas/Administrador/Views/Personagem/Excluir.cshtml
@using Microsoft.AspNetCore.Identity
@model Arma

@{
    ViewData["Title"] = "Excluir Arma";
}

@inject SignInManager<RPGUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <a asp-controller="Arma" asp-action="Index">
        <svg id="btn-voltar" xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="#008C59" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"></path>
        </svg>
    </a>
    <div class="container cartao">
        <div class="cartao-topo adicionar">
            <h2 class="cartao-titulo">@ViewData["Title"]</h2>
        </div>

        <div id="cartao-conteudo" class="cartao-conteudo adicionar">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>

                <label asp-for="Nome" class="label-cadastro"></label>
                <input asp-for="Nome" class="input-cadastro" disabled />

                <label asp-for="Descricao" class="label-cadastro"></label>
                <div class="descricao">
                    <textarea asp-for="Descricao" class="input-cadastro" disabled></textarea>
                </div>

                <label asp-for="Dano" class="label-cadastro"></label>
                <input asp-for="Dano" class="input-cadastro number" disabled />

                <label asp-for="Alcance" class="label-cadastro"></label>
                <input asp-for="Alcance" class="input-cadastro number" disabled />

                <label asp-for="UsaMunicao" class="label-cadastro"></label>
                <input type="text" asp-for="UsaMunicao" class="input-cadastro" disabled value="@(Model.UsaMunicao ? "Sim" : "Não")" />

                <label asp-for="TipoMunicao" class="label-cadastro"></label>
                <input asp-for="TipoMunicao" class="input-cadastro" disabled />

                <label asp-for="MunicaoMaxima" class="label-cadastro"></label>
                <input asp-for="MunicaoMaxima" class="input-cadastro number" disabled />

                <label asp-for="MunicaoAtual" class="label-cadastro"></label>
                <input asp-for="MunicaoAtual" class="input-cadastro number" disabled />

                <div class="container-botao">
                    <button type="submit" class="col-5 botao-submit">Excluir</button>
                </div>
            </form>
        </div>
    </div>
}
else
{
    if (User.IsInRole("Administrador"))
    {
        <script type="text/javascript">
            window.location.href = "/Administrador/Home/Index";
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.location.href = "/Jogador/Home/Index";
        </script>
    }

}

ProjectRPG.Web/Areas/Administrador/Views/Personagem/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model List<Personagem>

@{
    ViewData["Title"] = "Visualizar Personagens";
}

@inject SignInManager<RPGUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <a asp-controller="Home" asp-action="Index">
        <svg id="btn-voltar" xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="#008C59" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z"></path>
        </svg>
    </a>
    <div class="container cartao">
        <div class="cartao-topo visualizar">
            <h2 class="cartao-titulo">@ViewData["Title"]</h2>
        </div>

        <div id="cartao-conteudo" class="cartao-conteudo visualizar">
            <div class="div-adicionar">
                <a asp-area="Administrador" asp-controller="Personagem" asp-action="AdicionarOuEditar" class="btn btn-dark btn-adicionar">
                    <svg id="icone-add" xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#f5f5f5" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"></path>
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"></path>
                    </svg>
                    Adicionar Personagem
                </a>
            </div>

            <div class="div-tabela">
                <table class="tabela table-striped">
                    <thead class="header-tabela">
                        <tr>
                            <th class="coluna-1">Jogador</th>
                            <th class="coluna-1">Nome</th>
                            <th class="coluna-2">Especie</th>
                            <th class="coluna-3">Aparencia</th>
                            <th class="coluna-4">PvTotal</th>
                            <th class="coluna-5">PvAtual</th>
                            <th class="coluna-6">Deslocamento</th>
                            <th class="coluna-7">Evasao</th>
                            <th class="coluna-8">Tag</th>
                            <th class="coluna-9">Armamentos</th>
                            <th class="coluna-9">Equipamentos</th>
                            <th class="coluna-9">Itens</th>
                            <th class="coluna-10">Opções</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        @foreach (var personagem in Model)
                        {
                            <tr>
                                <td class="coluna-1">@personagem.Nome</td>
                                <td class="coluna-2">@personagem.Nome</td>
                                <td class="coluna-3">@personagem.Especie</td>
                                <td class="coluna-4">@personagem.Aparencia</td>
                                <td class="coluna-6">@personagem.PvTotal</td>
                                <td class="coluna-7">@personagem.PvAtual</td>
                                <td class="coluna-8">@personagem.Deslocamento</td>
                                <td class="coluna-8">@personagem.Evasao</td>
                                <td class="coluna-8">@personagem.Tag</td>
                                <td class="coluna-8">
                                    @{
                                        if (personagem.Armamentos != null)

                                        {
                                            foreach (Arma item in personagem.Armamentos)
                                            {
                                                @item.Nome;
                                                <br />
                                            }
                                            
                                        }
                                }
                                </td>
                                <td class="coluna-8">
                                    @{
                                        if (personagem.Equipamentos != null)
                                        {
                                            foreach (Equipamento item in personagem.Equipamentos)
                                            {
                                                @item.Nome;
                                                <br />
                                            }
                                            
                                             
                                        }
                                    }
                                </td>
                                <td class="coluna-8">
                                    @{
                                        if (personagem.Itens != null)

                                        {
                                            foreach (Item item in personagem.Itens)
                                            {
                                                @item.Nome;
                                                <br />
                                            }
                                            
                                        }
                                    }
                                </td>

                                <td class="coluna-10">
                                    <div class="w-75 btn-group" role="group">
                                        <a asp-controller="Personagem" asp-action="AdicionarOuEditar" asp-route-id="@personagem.Id" class="btn btn-dark mx-2" id="btn-editar">
                                            <i class="bi bi-pencil-square"></i> Editar
                                        </a>
                                        <a asp-controller="Personagem" asp-action="Excluir" asp-route-id="@personagem.Id" class="btn btn-danger mx-2">
                                            <i class="bi bi-trash-fill"></i> Excluir
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>

    </div>
}
else
{
    if (User.IsInRole("Administrador"))
    {
        <script type="text/javascript">
            window.location.href = "/Administrador/Home/Index";
        </script>
    }
    else
    {
        <script type="text/javascript">
            window.location.href = "/Jogador/Home/Index";
        </script>
    }

}